from kivy.utils import get_color_from_hex as hex

# Generated by https://noeldelgado.github.io/shadowlord/#4e73ad

WHITE = (1, 1, 1, 1)

GRAY_100 = hex("#fcfdfe")
GRAY_200 = hex("#e6ecf4")
GRAY_300 = hex("#bbc9df")
GRAY_400 = hex("#8fa7cb")
GRAY_500 = hex("#6484b7")
GRAY_600 = hex("#446598")
GRAY_700 = hex("#31496d")
GRAY_800 = hex("#1e2c43")
GRAY_900 = hex("#0b1018")

PRIMARY = hex("#1893a1")
ACCENT = hex("#e13929")

TRANSPARENT = (0, 0, 0, 0)