#:kivy 2.1.0

<Videobox>:
    orientation: "vertical"
    BoxLayout:
        Button:
            text: "Sync Now"
            size_hint: None, None
            on_press: app.start_sync()

    Home:

<Home>:
    cols: 6
    spacing: 10


<SeriesThumbnail>:
    padding: 5
    orientation: "vertical"
    Imagebutton:
        source: root.poster_url
        on_press: root.show_series_detail()
    Label:
        text: root.label
    
